--/////////////////////////USUARIOS///////////////////////////////////////////

IF OBJECT_ID('USUARIOS', 'U') IS NOT NULL 
  DROP TABLE USUARIOS; 
GO

CREATE TABLE USUARIOS
(
  "ID"                          INT IDENTITY(1,1),
  "USER_NAME"                   VARCHAR(40) NOT NULL,
  "NOMBRE_COMPLETO"             VARCHAR(100) NOT NULL,
  "PASSWORD"		            VARCHAR(100) NOT NULL,
  "USUARIO_REGISTRO"            VARCHAR(50) DEFAULT SYSTEM_USER NOT NULL,
  "FECHA_REGISTRO"              DATETIME DEFAULT getdate() NOT NULL,
  "ESTADO_REGISTRO"				INT DEFAULT 1 NOT NULL, 
  CONSTRAINT USUARIOS_PK		PRIMARY KEY (ID)
);
--/////////////////////////CATEGORIA///////////////////////////////////////////

IF OBJECT_ID('CATEGORIA', 'U') IS NOT NULL 
  DROP TABLE CATEGORIA; 
GO

CREATE TABLE CATEGORIA
(
  "ID"                          INT IDENTITY(1,1),
  "NOMBRE"						VARCHAR(100) NOT NULL,
  "USUARIO_REGISTRO"            VARCHAR(50) DEFAULT SYSTEM_USER NOT NULL,
  "FECHA_REGISTRO"              DATETIME DEFAULT getdate() NOT NULL,
  "ESTADO_REGISTRO"				INT DEFAULT 1 NOT NULL, 
  CONSTRAINT CATEGORIA_PK		PRIMARY KEY (ID)
);

--/////////////////////////PRODUCTO///////////////////////////////////////////

IF OBJECT_ID('PRODUCTO', 'U') IS NOT NULL 
  DROP TABLE PRODUCTO; 
GO

CREATE TABLE PRODUCTO
(
  "ID"                          INT IDENTITY(1,1),
  "NOMBRE"						VARCHAR(100) NOT NULL,
  "ID_CATEGORIA"				INT NOT NULL,
  "USUARIO_REGISTRO"            VARCHAR(50) DEFAULT SYSTEM_USER NOT NULL,
  "FECHA_REGISTRO"              DATETIME DEFAULT getdate() NOT NULL,
  "ESTADO_REGISTRO"				INT DEFAULT 1 NOT NULL, 
  CONSTRAINT PRODUCTO_PK		PRIMARY KEY (ID)
);

ALTER TABLE PRODUCTO
  ADD CONSTRAINT "FK_PRODUCTO_TO_CATEGORIA" 
  FOREIGN KEY(ID_CATEGORIA)
  REFERENCES CATEGORIA("ID");
  
  
--/////////////////////////CARRITO_COMPRA///////////////////////////////////////////

IF OBJECT_ID('CARRITO_COMPRA', 'U') IS NOT NULL 
  DROP TABLE CARRITO_COMPRA; 
GO

CREATE TABLE CARRITO_COMPRA
(
  "ID"                          INT IDENTITY(1,1),
  "FECHA"						DATETIME NOT NULL,
  "ID_USUARIO"					INT NOT NULL,
  "USUARIO_REGISTRO"            VARCHAR(50) DEFAULT SYSTEM_USER NOT NULL,
  "FECHA_REGISTRO"              DATETIME DEFAULT getdate() NOT NULL,
  "ESTADO_REGISTRO"				INT DEFAULT 1 NOT NULL, 
  CONSTRAINT CARRITO_COMPRA_PK		PRIMARY KEY (ID)
);

ALTER TABLE CARRITO_COMPRA
  ADD CONSTRAINT "FK_CARRITO_COMPRA_TO_USUARIO" 
  FOREIGN KEY("ID_USUARIO")
  REFERENCES USUARIOS("ID");


--/////////////////////////H_PRODUCTO///////////////////////////////////////////

IF OBJECT_ID('H_PRODUCTO', 'U') IS NOT NULL 
  DROP TABLE H_PRODUCTO; 
GO

CREATE TABLE H_PRODUCTO
(
  "ID"                          INT IDENTITY(1,1),
  "CANTIDAD"					INT NOT NULL,
  "ID_PRODUCTO"					INT NOT NULL,
  "ID_CARRITO_COMPRA"			INT NOT NULL,
  "USUARIO_REGISTRO"            VARCHAR(50) DEFAULT SYSTEM_USER NOT NULL,
  "FECHA_REGISTRO"              DATETIME DEFAULT getdate() NOT NULL,
  "ESTADO_REGISTRO"				INT DEFAULT 1 NOT NULL, 
  CONSTRAINT H_PRODUCTO_PK		PRIMARY KEY (ID)
);

ALTER TABLE H_PRODUCTO
  ADD CONSTRAINT "FK_H_PRODUCTO_TO_PRODUCTO" 
  FOREIGN KEY("ID_PRODUCTO")
  REFERENCES PRODUCTO("ID");

ALTER TABLE H_PRODUCTO
  ADD CONSTRAINT "FK_H_PRODUCTO_TO_CARRITO_COMPRA" 
  FOREIGN KEY("ID_CARRITO_COMPRA")
  REFERENCES CARRITO_COMPRA("ID");

--//Procedure select 
--//Usuarios
USE [upc-database-rafael]
GO
CREATE or ALTER PROCEDURE SP_OBTENERUSUARIOS
AS
    SELECT * FROM USUARIOS
    WHERE ESTADO_REGISTRO = 1
GO
--//producto
USE [upc-database-rafael]
GO
CREATE or ALTER PROCEDURE SP_OBTENERPRODUCTO
AS
    SELECT * FROM PRODUCTO
    WHERE ESTADO_REGISTRO = 1
GO
USE [upc-database-rafael]
GO
--//Categoria
CREATE or ALTER PROCEDURE SP_OBTENERCATEGORIA
AS
    SELECT * FROM CATEGORIA
    WHERE ESTADO_REGISTRO = 1
GO
--//CarritoCompra
USE [upc-database-rafael]
GO
CREATE or ALTER PROCEDURE SP_OBTENERCARRITO_COMPRA
AS
    SELECT * FROM CARRITO_COMPRA
    WHERE ESTADO_REGISTRO = 1
GO
--//H_Producto
USE [upc-database-rafael]
GO
CREATE or ALTER PROCEDURE SP_OBTENERH_PRODUCTO
AS
    SELECT * FROM H_PRODUCTO
    WHERE ESTADO_REGISTRO = 1
GO

--//Procedure select by Id
--//Usuarios
USE [upc-database-rafael]
GO
CREATE or ALTER PROCEDURE SP_OBTENERUSUARIOSBYID
@Id INT
AS
    SELECT * FROM USUARIOS
    WHERE ID = @Id AND ESTADO_REGISTRO = 1
GO
--//Producto
USE [upc-database-rafael]
GO
CREATE or ALTER PROCEDURE SP_OBTENERPRODUCTOBYID
@Id INT
AS
    SELECT * FROM PRODUCTO
    WHERE ID = @Id AND ESTADO_REGISTRO = 1
GO
USE [upc-database-rafael]
GO
--//Categoria
CREATE or ALTER PROCEDURE SP_OBTENERCATEGORIABYID
@Id INT
AS
    SELECT * FROM CATEGORIA
    WHERE ID = @Id AND ESTADO_REGISTRO = 1
GO
--//CarritoCompra
USE [upc-database-rafael]
GO
CREATE or ALTER PROCEDURE SP_OBTENERCARRITO_COMPRABYID
@Id INT
AS
    SELECT * FROM CARRITO_COMPRA
    WHERE ID = @Id AND ESTADO_REGISTRO = 1
GO
--//H_Producto
USE [upc-database-rafael]
GO
CREATE or ALTER PROCEDURE SP_OBTENERH_PRODUCTOBYID
@Id INT
AS
    SELECT * FROM H_PRODUCTO
    WHERE ID = @Id AND ESTADO_REGISTRO = 1
GO

--//Procedimiento Insert
--//Usuarios
USE [upc-database-rafael]
GO
CREATE or ALTER PROCEDURE SP_INSERTARUSUARIOS
    @NOMBRE_COMPLETO VARCHAR(100),
    @USER_NAME VARCHAR(40),
    @PASSWORD VARCHAR(100)
AS
    INSERT INTO [dbo].[USUARIOS]([USER_NAME],[NOMBRE_COMPLETO], [PASSWORD]) VALUES (@USER_NAME,@NOMBRE_COMPLETO,@PASSWORD)
GO
--//Categoria
USE [upc-database-rafael]
GO
CREATE or ALTER PROCEDURE SP_INSERTARCATEGORIA
    @NOMBRE VARCHAR(100)
AS
    INSERT INTO [dbo].[CATEGORIA]([NOMBRE]) VALUES (@NOMBRE) 
GO
--//Producto
USE [upc-database-rafael]
GO
CREATE or ALTER PROCEDURE SP_INSERTARPRODUCTO
    @NOMBRE			VARCHAR(100),
    @ID_CATEGORIA	INT
AS
   INSERT INTO [dbo].[PRODUCTO]([NOMBRE], [ID_CATEGORIA]) VALUES (@NOMBRE,@ID_CATEGORIA)  
GO
--//CarritoCompra
USE [upc-database-rafael]
GO
CREATE or ALTER PROCEDURE SP_INSERTARCARRITO_COMPRA
    @ID_USUARIO INT
AS
   INSERT INTO [dbo].[CARRITO_COMPRA]([FECHA], [ID_USUARIO]) VALUES (getdate(), @ID_USUARIO)   
GO
--//H_Producto
USE [upc-database-rafael]
GO
CREATE or ALTER PROCEDURE SP_INSERTARH_PRODUCTO
    @CANTIDAD           INT,
    @ID_PRODUCTO        INT,
    @ID_CARRITO_COMPRA  INT
AS
   INSERT INTO [dbo].[H_PRODUCTO]([CANTIDAD], [ID_PRODUCTO], [ID_CARRITO_COMPRA]) VALUES (@CANTIDAD,@ID_PRODUCTO, @ID_CARRITO_COMPRA)  
GO
--//Procedimiento Update
--//Usuarios
USE [upc-database-rafael]
GO
CREATE or ALTER PROCEDURE SP_ACTUALIZARUSUARIOS
    @Id INT,
    @USER_NAME VARCHAR(40),
    @NOMBRE_COMPLETO VARCHAR(100),
    @PASSWORD VARCHAR(100)
AS
    UPDATE USUARIOS SET [USER_NAME] = @USER_NAME, NOMBRE_COMPLETO = @NOMBRE_COMPLETO, [PASSWORD] = @PASSWORD WHERE ID = @Id
GO
--//Categoria
USE [upc-database-rafael]
GO
CREATE or ALTER PROCEDURE SP_ACTUALIZARCATEGORIA
    @Id INT,
    @NOMBRE VARCHAR(100)
AS
    UPDATE CATEGORIA SET NOMBRE = @Nombre WHERE ID = @Id 
GO
--//Producto
USE [upc-database-rafael]
GO
CREATE or ALTER PROCEDURE SP_ACTUALIZARPRODUCTO
    @Id INT,
    @NOMBRE			VARCHAR(100),
    @ID_CATEGORIA	INT
AS
   UPDATE [PRODUCTO] SET NOMBRE = @Nombre, ID_CATEGORIA = @ID_CATEGORIA WHERE ID = @Id
GO
--//CarritoCompra
USE [upc-database-rafael]
GO
CREATE or ALTER PROCEDURE SP_ACTUALIZARCARRITO_COMPRA
    @Id INT,
    @ID_USUARIO INT
AS
   UPDATE [CARRITO_COMPRA] SET FECHA=getdate(), ID_USUARIO = @ID_USUARIO WHERE ID = @Id  
GO
--//H_Producto
USE [upc-database-rafael]
GO
CREATE or ALTER PROCEDURE SP_ACTUALIZARH_PRODUCTO
    @Id                 INT,
    @CANTIDAD           INT,
    @ID_PRODUCTO        INT,
    @ID_CARRITO_COMPRA  INT
AS
   UPDATE H_PRODUCTO SET CANTIDAD = @CANTIDAD, [ID_PRODUCTO] = @ID_PRODUCTO, [ID_CARRITO_COMPRA] = @ID_CARRITO_COMPRA WHERE ID = @Id
GO
--//Procedimiento Delete
--//Usuarios
USE [upc-database-rafael]
GO
CREATE or ALTER PROCEDURE SP_ELIMINARUSUARIOS
    @Id INT
AS
    UPDATE USUARIOS SET ESTADO_REGISTRO = 0 WHERE ID = @Id
GO
--//Categoria
USE [upc-database-rafael]
GO
CREATE or ALTER PROCEDURE SP_ELIMINARCATEGORIA
    @Id INT
AS
    UPDATE CATEGORIA SET ESTADO_REGISTRO = 0 WHERE ID = @Id 
GO
--//Producto
USE [upc-database-rafael]
GO
CREATE or ALTER PROCEDURE SP_ELIMINARPRODUCTO
    @Id INT
AS
   UPDATE [PRODUCTO] SET ESTADO_REGISTRO = 0 WHERE ID = @Id
GO
--//CarritoCompra
USE [upc-database-rafael]
GO
CREATE or ALTER PROCEDURE SP_ELIMINARCARRITO_COMPRA
    @Id INT
AS
   UPDATE [CARRITO_COMPRA] SET ESTADO_REGISTRO = 0 WHERE ID = @Id 
GO
--//H_Producto
USE [upc-database-rafael]
GO
CREATE or ALTER PROCEDURE SP_ELIMINARH_PRODUCTO
    @Id                 INT
AS
   UPDATE H_PRODUCTO SET ESTADO_REGISTRO = 0 WHERE ID = @Id
GO

--/////////////////////////PROYECTO FINAL///////////////////////////////////////////

--/////////////////////////ALUMNO///////////////////////////////////////////

IF OBJECT_ID('ALUMNO', 'U') IS NOT NULL 
  DROP TABLE ALUMNO; 
GO

CREATE TABLE ALUMNO
(
  "ID"                          INT IDENTITY(1,1),
  "NOMBRE_COMPLETO"				VARCHAR(100) NOT NULL,
  "CURSO"                       VARCHAR(100) NOT NULL,
  "GESTION"                     INT NOT NULL,
  "USUARIO_REGISTRO"            VARCHAR(50) DEFAULT SYSTEM_USER NOT NULL,
  "FECHA_REGISTRO"              DATETIME DEFAULT getdate() NOT NULL,
  "ESTADO_REGISTRO"				INT DEFAULT 1 NOT NULL, 
  CONSTRAINT ALUMNO_PK		PRIMARY KEY (ID)
);

--/////////////////////////PAGO///////////////////////////////////////////

IF OBJECT_ID('PAGO', 'U') IS NOT NULL 
  DROP TABLE PAGO; 
GO
CREATE TABLE PAGO
(
  "ID"                          INT IDENTITY(1,1),
  "FECHA"						DATETIME NOT NULL,
  "MONTO"                       INT NOT NULL,
  "ID_ALUMNO"   				INT NOT NULL,
  "USUARIO_REGISTRO"            VARCHAR(50) DEFAULT SYSTEM_USER NOT NULL,
  "FECHA_REGISTRO"              DATETIME DEFAULT getdate() NOT NULL,
  "ESTADO_REGISTRO"				INT DEFAULT 1 NOT NULL, 
  CONSTRAINT PAGO_PK    		PRIMARY KEY (ID)
);

ALTER TABLE PAGO
  ADD CONSTRAINT "FK_PAGO_TO_ALUMNO" 
  FOREIGN KEY(ID_ALUMNO)
  REFERENCES ALUMNO("ID");
  
--//ALUMNO
--// OBTENER
USE [upc-database-rafael]
GO
CREATE or ALTER PROCEDURE SP_OBTENERALUMNO
AS
    SELECT * FROM ALUMNO
    WHERE ESTADO_REGISTRO = 1
GO
USE [upc-database-rafael]
GO
--//OBTENER BY ID
CREATE or ALTER PROCEDURE SP_OBTENERALUMNOBYID
@ID INT
AS
    SELECT * FROM ALUMNO
    WHERE ID = @ID AND ESTADO_REGISTRO = 1
GO
USE [upc-database-rafael]
GO
--//INSERTAR
USE [upc-database-rafael]
GO
CREATE or ALTER PROCEDURE SP_INSERTARALUMNO
    @NOMBRE_COMPLETO			VARCHAR(100),
    @CURSO                      VARCHAR(100),
    @GESTION                    INT
AS
   INSERT INTO [dbo].[ALUMNO](NOMBRE_COMPLETO,CURSO,GESTION) VALUES (@NOMBRE_COMPLETO,@CURSO, @GESTION)  
GO
--//MODIFICAR
USE [upc-database-rafael]
GO
CREATE or ALTER PROCEDURE SP_ACTUALIZARALUMNO
    @ID                 INT,
    @NOMBRE_COMPLETO	VARCHAR(100),
    @CURSO              VARCHAR(100),
    @GESTION            INT
AS
   UPDATE [ALUMNO] SET @NOMBRE_COMPLETO = @NOMBRE_COMPLETO, CURSO=@CURSO,GESTION=@GESTION WHERE ID = @ID
GO
--//ELIMINAR
USE [upc-database-rafael]
GO
CREATE or ALTER PROCEDURE SP_ELIMINARALUMNO
    @ID         INT
AS
   UPDATE ALUMNO SET ESTADO_REGISTRO = 0 WHERE ID = @Id
GO

--//PAGO
--// OBTENER
USE [upc-database-rafael]
GO
CREATE or ALTER PROCEDURE SP_OBTENERPAGO
AS
    SELECT * FROM PAGO
    WHERE ESTADO_REGISTRO = 1
GO
USE [upc-database-rafael]
GO
--//OBTENER BY ID
CREATE or ALTER PROCEDURE SP_OBTENERPAGOBYID
@ID INT
AS
    SELECT * FROM PAGO
    WHERE ID = @ID AND ESTADO_REGISTRO = 1
GO
USE [upc-database-rafael]
GO
--//INSERTAR
USE [upc-database-rafael]
GO
CREATE or ALTER PROCEDURE SP_INSERTARPAGO
    @MONTO      INT,
    @ID_ALUMNO  INT
AS
   INSERT INTO [dbo].[PAGO](FECHA,MONTO,ID_ALUMNO) VALUES (GETDATE(),@MONTO, @ID_ALUMNO)  
GO
--//MODIFICAR
USE [upc-database-rafael]
GO
CREATE or ALTER PROCEDURE SP_ACTUALIZARPAGO
    @ID         INT,
    @MONTO      INT,
    @ID_ALUMNO  INT
AS
   UPDATE [PAGO] SET FECHA=GETDATE(), MONTO=@MONTO, ID_ALUMNO=@ID_ALUMNO WHERE ID = @ID
GO
--//ELIMINAR
USE [upc-database-rafael]
GO
CREATE or ALTER PROCEDURE SP_ELIMINARPAGO
    @ID         INT
AS
   UPDATE PAGO SET ESTADO_REGISTRO = 0 WHERE ID = @Id
GO

EXEC SP_INSERTARALUMNO 'Rodolfo Cruz','5to A',2023
EXEC SP_OBTENERALUMNO
EXEC SP_INSERTARPAGO 25,1
EXEC SP_OBTENERPAGO